config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(set_params)
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(set_params)
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_params
    params.require(:post).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Entrainement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootsrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Welcome to Posts</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<section>
<h1 class="h1_form_new">Edit a post</h1>
  <div class="form_new">
    <%= form_for @post do |f| %>
      <div class="form-group">
        <label>Title of the post</label>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Description of the post</label>
        <%= f.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Edit the post</button>
      </div>
    <% end %>
  </div>
</section>

app/views/posts/index.html.erb
<section style="padding: 5rem;">
  <h1> All posts </h1>


  <% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <p><%= post.description %></p>
    <p>
      <a href="<%= post_path(post.id) %>" class="btn btn-primary"> Read the post</a>
      <a href="<%= edit_post_path(post.id)  %>" > Edit </a>
      <%= link_to "Delete", post_path(post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>

    </p>
  <% end %>
</section>

app/views/posts/new.html.erb
<h1>Create a post</h1>

<%= form_for @post do |f| %>
  <div class="form-group">
    <label>Title of the post</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Description of the post</label>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit">Create the post</button>
  </div>
<% end %>

app/views/posts/show.html.erb
<h2> <%= @post.title %> </h2>

<p><%= @post.description %></p>


<%= link_to "Edit", edit_post_path(@post), class:"btn btn-warning" %>
<%= link_to "Delete", post_path(@post), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "btn btn-danger" %>